update

diff --git a/files/.local/bin/to7zip b/files/.local/bin/to7zip
--- a/files/.local/bin/to7zip
+++ b/files/.local/bin/to7zip
@@ -2,7 +2,7 @@
 
 print_help() {
 	echo ""
-	echo "Convert an archive to the 7zip format, or create a new archive"
+	echo "Convert an archive from one format to another"
 	echo ""
 	echo "Usage:   to7zip [options] ...files"
 	echo ""
@@ -11,17 +11,19 @@ print_help() {
 	echo "   -d, --delete-old   Delete converted file"
 	echo "   -f, --force        Replace the file with the converted file even if the file exists"
 	echo "   -r, --rezip        Extract and archive again even if the converted file is already a 7zip archive"
+	echo "   -F, --format       The format of the output"
     echo "   -t, --thread       Set the number of threads for archive extraction and creation (default: $thread_count)"
 	echo ""
 }
 
-short_args=hdfrt:
-long_args=help,delete-old,force,rezip,thread:
+short_args=hdfrF:t:
+long_args=help,delete-old,force,rezip,format:,thread:
 
 # default
 rezip=
 delete_old=
 force=
+zip_args=
 thread_count=8
 params=""
 
@@ -50,6 +52,20 @@ while true; do
             rezip=y
 			shift
 			;;
+		-F|--format)
+            case "$2" in
+                7z)
+                    ;;
+                zip)
+                    zip_args="-tzip"
+                    output_ext="zip"
+                    ;;
+                *)
+                    echo "Unknown format: $2"
+                    exit 1
+            esac
+			shift 2
+			;;
 		-t|--thread)
             thread_count="$2"
 			shift 2
@@ -66,9 +82,14 @@ done
 
 out_dir="$PWD"
 
+if [[ -z "$zip_args" ]]; then
+    zip_args="-t7z -m0=lzma2 -ms=on"
+    output_ext=7z
+fi
+
 for f in "$@"; do
     tmp_dir="$(mktemp -d "$PWD/to7zip.XXX")"
-    output="$(echo "$f" | sed -E 's/\.(zip|rar|7z)$//g').7z"
+    output="$(echo "$f" | sed -E 's/\.(7z|tar\.gz|zip|rar)$//g').$output_ext"
     backup_file="$output".backup
     do_backup=
 
@@ -88,7 +109,12 @@ for f in "$@"; do
         fi
     fi
 
-    if [[ "$f" =~ \.tar|gz|bz2|zip|7z$ ]]; then
+    if [[ "$f" =~ \.tar[^/]*$ ]]; then
+        if ! tar -xf "$f" -C "$tmp_dir" >/dev/null; then
+            echo "$f : extract failed"
+            continue
+        fi
+    elif [[ "$f" =~ \.tar|gz|bz2|zip|7z$ ]]; then
         if ! 7z e -mmt="$thread_count" -o"$tmp_dir" "$f" >/dev/null; then
             echo "$f : extract failed"
             continue
@@ -107,7 +133,7 @@ for f in "$@"; do
     fi
 
     pushd "$tmp_dir" >/dev/null
-    7z a -t7z -m0=lzma2 -mx=9 -ms=on -mmt="$thread_count" "$out_dir/$output" >/dev/null
+    7z a $zip_args -mx=9 -mmt="$thread_count" "$out_dir/$output" >/dev/null
     return_val=$?
     popd >/dev/null
     if [[ $return_val -eq 0  ]]; then
